version: '3'

services:
     
   emailcheck:
     build: ./emailcheck
     ports:
     - "9000:9000"

   passwordcheck:
     build: ./passwordcheck
     ports:
     - "9001:9001"
     
   role:
     build: ./role
     ports:
     - "9002:9002"

   auth:
     build: ./authentication
     ports:
     - "9003:9003"
